import { useMemo, useState, type CSSProperties } from "react";
import { TradingChart } from "./components/CandlestickChart";
import { Mark, Sidebar, Topbar } from "./components/Navigation";
import type { Page } from "./types/navigation";
type Side = "buy" | "sell";

const marketRows = [
  ["S", "SOL/USD", "Solana", "$148.64", "+4.82%", "up"],
  ["₿", "BTC/USD", "Bitcoin", "$67,382.10", "+1.24%", "up"],
  ["E", "ETH/USD", "Ethereum", "$3,524.66", "−0.38%", "down"],
  ["A", "AXIS/USD", "Axis", "$2.741", "−2.06%", "down"],
] as const;


function OrderBook() { const rows = [["149.14", "3.260", "485.91"], ["149.05", "0.840", "125.25"], ["148.92", "6.120", "911.49"], ["148.81", "2.700", "401.79"], ["148.72", "1.540", "229.01"]]; return <section className="book-panel panel"><div className="panel-heading"><strong>Order book</strong><button>▤ 0.01⌄</button></div><div className="book-head"><span>PRICE (USD)</span><span>AMOUNT (SOL)</span><span>TOTAL</span></div><div className="book-list asks">{rows.map((row, i) => <div className="book-row" key={row[0]} style={{ "--depth": `${30 + i * 12}%` } as CSSProperties}><span>{row[0]}</span><span>{row[1]}</span><span>{row[2]}</span></div>)}</div><div className="spread"><b>148.64</b><span>≈ $148.64</span><em>↗</em></div><div className="book-list bids">{rows.map((row, i) => <div className="book-row" key={row[0]} style={{ "--depth": `${68 - i * 9}%` } as CSSProperties}><span>{(148.57 - i * .14).toFixed(2)}</span><span>{row[1]}</span><span>{row[2]}</span></div>)}</div></section>; }

function OrderForm() { const [side, setSide] = useState<Side>("buy"); const [amount, setAmount] = useState(""); const [price, setPrice] = useState("148.64"); const [type, setType] = useState("Limit"); const total = useMemo(() => ((Number(price) * Number(amount)) || 0).toFixed(2), [price, amount]); return <section className="order-panel panel"><div className="order-side-tabs"><button onClick={() => setSide("buy")} className={side === "buy" ? "buy-active" : ""}>Buy SOL</button><button onClick={() => setSide("sell")} className={side === "sell" ? "sell-active" : ""}>Sell SOL</button></div><div className="order-type-tabs">{["Limit", "Market", "Stop limit"].map(item => <button key={item} className={type === item ? "type-active" : ""} onClick={() => setType(item)}>{item}</button>)}</div><label>Available <span>{side === "buy" ? "4,201.32 USD" : "12.840 SOL"}</span></label><div className="field"><span>Price</span><input disabled={type === "Market"} value={type === "Market" ? "Market" : price} onChange={e => setPrice(e.target.value)}/><b>USD</b></div><div className="field"><span>Amount</span><input value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00"/><b>SOL</b></div><div className="percent-row">{[25, 50, 75, 100].map(n => <button key={n} onClick={() => setAmount((28.27 * n / 100).toFixed(3))}>{n === 100 ? "MAX" : `${n}%`}</button>)}</div><div className="field total-field"><span>Total</span><input value={total} readOnly/><b>USD</b></div><p className="fee-note">Est. fee <span>{(Number(total) * .002).toFixed(2)} USD</span></p><button className={`place-order ${side}`}>{side === "buy" ? "Buy" : "Sell"} SOL <span>→</span></button></section>; }

function TradePage() { return <><div className="market-header"><div className="asset-title"><div className="sol-icon">S</div><div><p>SOL / USD <span>Spot</span></p><small>Solana</small></div><button className="star">☆</button></div><div className="headline-price"><strong>$148.64</strong><span>+4.82% <em>+$6.82 today</em></span></div>{[["24h HIGH", "$151.23"], ["24h LOW", "$139.87"], ["24h VOLUME", "$24.8M"]].map(([label, value]) => <div className="stat" key={label}><small>{label}</small><b>{value}</b></div>)}</div><div className="trade-grid"><TradingChart /><OrderBook /><OrderForm /><section className="trades-panel panel"><div className="panel-heading"><strong>Market trades</strong><button>⌄</button></div><div className="book-head"><span>PRICE</span><span>AMOUNT</span><span>TIME</span></div>{[["148.64", "0.182", "10:42:08", "positive"], ["148.62", "1.840", "10:42:06", "negative"], ["148.67", ".420", "10:42:03", "positive"], ["148.59", "2.000", "10:42:01", "negative"], ["148.61", ".062", "10:41:58", "positive"]].map(t => <div className="trade-row" key={t[2]}><b className={t[3]}>{t[0]}</b><span>{t[1]}</span><span>{t[2]}</span></div>)}<button className="view-all">View all trades →</button></section></div><Activity /></>; }

function Activity() { return <section className="activity panel"><div className="activity-tabs"><button className="active-tab">Open orders <span>2</span></button><button>Order history</button><button>Fills</button></div><div className="activity-head"><span>MARKET</span><span>TYPE</span><span>SIDE</span><span>PRICE</span><span>FILLED</span><span>STATUS</span><span /></div>{[["SOL/USD", "Limit", "Buy", "$143.20", "0.00 / 4.00", "Open"], ["BTC/USD", "Limit", "Sell", "$68,500", "0.01 / 0.05", "Partial"]].map(row => <div className="order-row" key={row[0]}>{row.map((item, i) => <span key={i} className={item === "Buy" ? "positive" : item === "Sell" ? "negative" : ""}>{item}</span>)}<button>Cancel</button></div>)}</section>; }

function MarketsPage({ onTrade }: { onTrade: () => void }) { return <div className="page-content"><div className="page-title"><span>Markets</span><p>Follow live movement across your available spot pairs.</p></div><div className="market-hero"><p>MARKET PULSE</p><strong>Top movers<br /><em>in the last 24h.</em></strong><span>+4.82% <small>SOL/USD leads today</small></span></div><section className="table-panel panel"><div className="market-table-head"><span>MARKET</span><span>LAST PRICE</span><span>24H CHANGE</span><span>24H VOLUME</span><span /></div>{marketRows.map(row => <div className="market-table-row" key={row[1]}><div><i className={`table-coin ${row[5]}`}>{row[0]}</i><span><b>{row[1]}</b><small>{row[2]}</small></span></div><strong>{row[3]}</strong><em className={row[5] === "up" ? "positive" : "negative"}>{row[4]}</em><span>$24.8M</span><button onClick={onTrade}>Trade →</button></div>)}</section></div>; }

function WalletPage({ onAuth }: { onAuth: () => void }) { return <div className="page-content"><div className="page-title"><span>Wallet</span><p>Your balances are held securely and ready to trade.</p></div><section className="wallet-overview"><div><small>TOTAL PORTFOLIO VALUE</small><strong>$6,108.70</strong><p className="positive">+ $281.42 <span>this week</span></p></div><button className="deposit-button" onClick={onAuth}>+ Add funds</button></section><section className="balance-cards">{[["USD", "US Dollar", "4,201.32", "$4,201.32", "usd"], ["S", "Solana", "12.840", "$1,908.15", "sol"], ["₿", "Bitcoin", "0.000", "$0.00", "btc"]].map(c => <article className="balance-card panel" key={c[1]}><i className={`table-coin ${c[4]}`}>{c[0]}</i><span>{c[1]}<small>{c[2]}</small></span><strong>{c[3]}</strong><button>⋯</button></article>)}</section><section className="deposit-brief panel"><div><p>FUND YOUR ACCOUNT</p><strong>Deposit INR through Razorpay.</strong><span>Funds are converted to USD after secure payment confirmation.</span></div><button onClick={onAuth}>Make a deposit →</button></section></div>; }

function HistoryPage() { return <div className="page-content"><div className="page-title"><span>Activity</span><p>Every order, fill, and balance movement in one place.</p></div><section className="history-filter panel"><button className="active-filter">All activity</button><button>Orders</button><button>Fills</button><button>Deposits</button><span>Last 30 days⌄</span></section><section className="history-list panel">{[["Filled", "Bought 0.840 SOL", "SOL/USD · Market order", "+0.840 SOL", "Today, 10:42"], ["Deposit", "INR deposit completed", "Razorpay · #pay_Q8F2", "+$120.00", "Yesterday, 16:08"], ["Cancelled", "Sell order cancelled", "BTC/USD · Limit $68,500", "0.00", "Jul 21, 09:15"]].map(item => <div className="history-item" key={item[1]}><i className={item[0].toLowerCase()}>{item[0] === "Filled" ? "↗" : item[0] === "Deposit" ? "+" : "×"}</i><span><b>{item[1]}</b><small>{item[2]}</small></span><em className={item[3].startsWith("+") ? "positive" : ""}>{item[3]}</em><time>{item[4]}</time></div>)}</section></div>; }

function AuthPage({ onBack }: { onBack: () => void }) { const [signup, setSignup] = useState(false); return <div className="auth-page"><div className="auth-visual"><div className="auth-brand"><Mark /> COINLATTICE</div><div><p>THE EXCHANGE<br />FOR <em>DECISIVE</em><br />TRADERS.</p><span>Built around quick execution, clear balances, and your next move.</span></div><small>© 2026 Coinlattice · Spot markets</small></div><div className="auth-card-wrap"><button className="back-button" onClick={onBack}>← Back to terminal</button><div className="auth-card"><small>{signup ? "CREATE AN ACCOUNT" : "WELCOME BACK"}</small><h1>{signup ? "Start trading." : "Sign in to trade."}</h1><p>{signup ? "Create an account to access Coinlattice." : "Enter your account details to continue."}</p>{signup && <label>Name<input placeholder="Your display name" /></label>}<label>Email address<input type="email" placeholder="you@example.com" /></label><label>Password<input type="password" placeholder="••••••••" /></label>{!signup && <a href="#reset">Forgot password?</a>}<button className="auth-submit">{signup ? "Create account" : "Sign in"} <span>→</span></button><div className="auth-switch">{signup ? "Already have an account?" : "New to Coinlattice?"} <button onClick={() => setSignup(!signup)}>{signup ? "Sign in" : "Create one"}</button></div></div></div></div>; }

function App() { const [page, setPage] = useState<Page>("trade"); const [collapsed, setCollapsed] = useState(false); if (page === "auth") return <AuthPage onBack={() => setPage("trade")} />; return <main className="terminal-shell"><Sidebar page={page} onPage={setPage} collapsed={collapsed} onToggle={() => setCollapsed(!collapsed)} /><section className="workspace"><Topbar onAuth={() => setPage("auth")} onToggle={() => setCollapsed(!collapsed)} />{page === "trade" && <TradePage />}{page === "markets" && <MarketsPage onTrade={() => setPage("trade")} />}{page === "wallet" && <WalletPage onAuth={() => setPage("auth")} />}{page === "history" && <HistoryPage />}</section></main>; }

export default App;
